resume:
    resource: "@HRResumeBundle/Resources/config/routing.xml"
    prefix:   /

skill:
    resource: "@HRSkillBundle/Resources/config/routing.xml"
    prefix:   /

education:
    resource: "@HREducationBundle/Resources/config/routing.xml"
    prefix:   /

position:
    resource: "@HRPositionBundle/Resources/config/routing.xml"
    prefix:   /

user:
    resource: "@HRUserBundle/Resources/config/routing.xml"
    prefix:   /

home:
    pattern: /