oauth:
    resource: "@HROAuthBundle/Resources/config/routing.xml"
    prefix:   /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

oauth_weibo:
    pattern: /login/weibo

notification:
    resource: "@HRNotificationBundle/Resources/config/routing.xml"
    prefix:   /

page:
    resource: "@HRPageBundle/Resources/config/routing.xml"
    prefix:   /

location:
    resource: "@HRLocationBundle/Resources/config/routing.xml"
    prefix:   /

job:
    resource: "@HRJobBundle/Resources/config/routing.xml"
    prefix:   /

skill:
    resource: "@HRSkillBundle/Resources/config/routing.xml"
    prefix:   /

education:
    resource: "@HREducationBundle/Resources/config/routing.xml"
    prefix:   /

position:
    resource: "@HRPositionBundle/Resources/config/routing.xml"
    prefix:   /

user:
    resource: "@HRUserBundle/Resources/config/routing.xml"
    prefix:   /