oauth:
    resource: "@HROAuthBundle/Resources/config/routing.xml"

notification:
    resource: "@HRNotificationBundle/Resources/config/routing.xml"

page:
    resource: "@HRPageBundle/Resources/config/routing.xml"

location:
    resource: "@HRLocationBundle/Resources/config/routing.xml"

position:
    resource: "@HRPositionBundle/Resources/config/routing.xml"

skill:
    resource: "@HRSkillBundle/Resources/config/routing.xml"

education:
    resource: "@HREducationBundle/Resources/config/routing.xml"

career:
    resource: "@HRCareerBundle/Resources/config/routing.xml"

user:
    resource: "@HRUserBundle/Resources/config/routing.xml"
