page:
    resource: "@HRPageBundle/Resources/config/routing.xml"
    prefix:   /

location:
    resource: "@HRLocationBundle/Resources/config/routing.xml"
    prefix:   /

job:
    resource: "@HRJobBundle/Resources/config/routing.xml"
    prefix:   /

resume:
    resource: "@HRResumeBundle/Resources/config/routing.xml"
    prefix:   /

skill:
    resource: "@HRSkillBundle/Resources/config/routing.xml"
    prefix:   /

education:
    resource: "@HREducationBundle/Resources/config/routing.xml"
    prefix:   /

position:
    resource: "@HRPositionBundle/Resources/config/routing.xml"
    prefix:   /

user:
    resource: "@HRUserBundle/Resources/config/routing.xml"
    prefix:   /